### ISSUE TITLE
你好，关于课程

### ISSUE THREAD

**Issue by jawa10** [williamjiamin/williamjiamin#1]
你好，我最近找到你们的课程，觉得挺不错，购买前想咨询咨询一下，但是发现你们的客服，无论是“lxodxgj”， 还是企业微信的“乐学偶得校花”  ，都完全不搭理人。
所以我就在网络上搜索了一下，看到很多人都说客服非常差劲。比如知乎上这个话题（https://www.zhihu.com/question/439582808） ，三个回答中有两个都提到这一点。看来这是共性问题了，希望能够解决。
没有别的渠道能够联系到你，只好在github上留言了。祝好~

**Comment by williamjiamin** [comment]
感谢您的反馈，给您造成不好体验深表歉意，我会对此进行核查并督促运营团队改进。
